### ISSUE TITLE
Candidate fairness

### ISSUE THREAD

**Issue by jasrodis** [github4sanjay/hospital-simulator#1]
Dear repository owner,

It would be really appreciated if you could help us by removing this public repository. This is a public solution to the coding challenge exercise that we use in order to evaluate candidates during the recruitment process.

Unfortunately, having such a public solution is not fair play for new candidates. We really hope you understand.

Many thanks in advance,
Best regards,
Iason
Hiring team at Evooq

**Comment by jasrodis** [comment]
Dear repository owner,

It would be really appreciated if you could help us by removing this public repository. This is a public solution to the coding challenge exercise that we use in order to evaluate candidates during the recruitment process.

Unfortunately, having such a public solution is not fair play for new candidates. We really hope you understand.

Many thanks in advance,
Best regards,
Iason
Hiring team at Evooq

**Comment by github4sanjay** [comment]
@jasrodis Its also not fair to give the assignment and if candidate submits the solution the hiring team never gives any feedback. A candidate gives its precious time in interview process and at the end the hiring team just shuts the communication channel, is it fair ?
